# Generated by Django 5.2.7 on 2025-10-11 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
                ('labels', models.TextField(help_text='Comma-separated labels for the image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.IntegerField(choices=[(1, 'Liked'), (3, 'Starred')])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.collection')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.image')),
            ],
            options={
                'unique_together': {('collection', 'image')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='images',
            field=models.ManyToManyField(through='recommendation.CollectionImage', to='recommendation.image'),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('position', models.IntegerField(help_text='Position in the recommendation list (1 is most similar)')),
                ('added_to_collection', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.image')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recommended_images', models.ManyToManyField(related_name='recommended_in_sessions', through='recommendation.Recommendation', to='recommendation.image')),
                ('reference_images', models.ManyToManyField(related_name='reference_for_sessions', to='recommendation.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recommendation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.recommendationsession'),
        ),
    ]
